# Generated by Django 2.2.4 on 2019-08-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='permissions',
            field=models.CharField(blank=True, choices=[('0', 'Collaborator'), ('1', 'Administrator')], default='0', max_length=1),
        ),
    ]
