# Generated by Django 2.2.4 on 2019-08-28 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('departament', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.Estate')),
            ],
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diameter', models.IntegerField()),
                ('height', models.IntegerField()),
                ('health', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.Plot')),
            ],
        ),
    ]
